name: .NET

on: [push, pull_request]

jobs:

  Build:
    strategy:
      matrix:
        include:
          - { path: Binding, plugin: ScriptRunner }
          - { path: Filter, plugin: MeL }
          - { path: Filter, plugin: PrecisionControl }
          - { path: Filter, plugin: Reconstructor }
          - { path: OutputMode, plugin: TouchEmu }
          - { path: OutputMode, plugin: VMultiMode }
          - { path: OutputMode, plugin: WindowsInk }

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '6.0'

    - name: Build
      env:
        path: ${{ matrix.path }}
        plugin: ${{ matrix.plugin }}
      run: ./build.sh --single "$path/$plugin" --no-zip

    - uses: actions/upload-artifact@main
      with:
        name: ${{ matrix.plugin }}
        path: |
          ./build/${{ matrix.plugin }}/*
